name: NPM_Build_Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 10.7.0
      - name: Install dependencies
        run: |
          pwd
          npm ci
        working-directory: ./path-to-your-project-directory  # Update this line if necessary
      - name: Build project
        run: |
          pwd
          npm run build
        working-directory: ./path-to-your-project-directory  # Update this line if necessary
